- src/user/dto/create-user.dto.ts
- src/user/entities/user.entity.ts
- src/user/user.controller.ts
- src/user/user.service.ts
#6 
**진행사항**
- pull request 피드백 수정
- 스웨거 수정
- entity 카멜케이스 수정
> (user/signup) 피드백 수정 반영

- src/accounts/accounts.controller.ts
- src/accounts/accounts.service.ts
- src/accounts/dto/update-account.dto.ts
- src/accounts/entities/account.entity.ts
- src/user/entities/user.entity.ts
#9 
**진행사항**
1. 나의 모든 계좌 조회
- id, name, point, userId 반환 
2. 나의 특정 계좌 조회
- id, name,point,userId 반환
3. 나의 특정 계좌 수정 
- 계좌 이름만 수정 가능
4. 나의 특정 계좌 삭제
**특이사항**
1. 로그인 기능 완료 시 UserInfo 데코레이터에서 userId 값 활용할 예정 @kimminjae981002 
2. 주식 종목 관련 기능 완료 시 계좌 조회에서 아래 데이터 추가할 예정
- 나의 모든 주식 계좌 조회
예수금(point) + 주식 평가 금액 = 총 평가금액
- 나의 특정 계좌 조회
계좌에서 보유한 종목들
3. 계좌 삭제 시 보유한 종목들도 함께 삭제 가능하도록 cascade 적용 필요
> (account) 내 계좌 조회, 수정, 삭제 기능 추가

- src/accounts/accounts.controller.ts
- src/accounts/accounts.service.ts
- src/accounts/entities/account.entity.ts
#9
**진행사항**
**1) 로그인 시 Req 에서 유저 정보 활용**
- UserInfo 데코레이터에서 현재 로그인 된 유저의 정보를 확인
- API 호출 시 유저 아이디를 가져옴
**2) 계좌 생성 시 계좌번호 추가**
- 유저가 이름 외의 공정된 계좌 구분 값을 확인할 필요가 있다고 판단
> (account/create) 계좌 생성 시 계좌번호 추가

- src/accounts/accounts.module.ts
- src/app.module.ts
- src/auth/roles.guard.ts
- src/common/decorator/roles.decorator.ts
- src/configs/database.config.ts
- src/notice/dto/create-notice.dto.ts
- src/notice/dto/update-notice.dto.ts
- src/notice/entities/notice.entity.ts
- src/notice/notice.controller.ts
- src/notice/notice.module.ts
- src/notice/notice.service.ts
- src/user/entities/user.entity.ts
- 공지사항 CRUD 기능 구현
- 조회시 내림차순
- 공지사항 작성, 수정, 삭제 시 role을 확인해서 관리자(admin)일 경우만 작동
- RolesGuard가 JwtAuthGuard역할을 할 수 있게 코드 수정
> (notice/create) 공지사항 백엔드 CRUD

- src/app.module.ts
- src/comment/comment.controller.ts
- src/comment/comment.module.ts
- src/comment/comment.service.ts
- src/comment/dto/create-comment.dto.ts
- src/comment/dto/update-comment.dto.ts
- src/comment/entities/comment.entity.ts
- src/configs/database.config.ts
- src/post/entities/post.entity.ts
- src/user/entities/user.entity.ts
- 댓글 작성
- 댓글 조회
- database.config.ts에 post모듈을 추가했음에도 comment모듈에 post를 추가하지 않으면 에러남
> (Comment) 댓글 작성, 조회기능 구현

- src/comment/comment.controller.ts
- src/comment/comment.service.ts
- src/comment/entities/comment.entity.ts
- src/notice/notice.controller.ts
- src/notice/notice.service.ts
- 댓글수정기능구현
- 댓글삭제기능구현
- 코드컨벤션맞춰서 notice 컨트롤러 수정
> (comment) 댓글 수정, 삭제 기능 구현

- assets/css/signup.css
- assets/js/signin-email-verify.js
- assets/js/signup.js
- assets/views/login.html
- assets/views/signin-email-verify.html
- assets/views/signup.html
- src/user/dto/create-user.dto.ts
- src/user/user.controller.ts
- src/user/user.service.ts
* 진행상황
1) 회원가입 시 이메일 / 닉네임 중복체크
2) 회원가입 시 닉네임 / 이름 글자수 제한
3) 회원가입 시 비밀번호 특수문자 / 글자수 제한
* 특이사항
1) 회원가입 시 가입한 이메일에 메일 발송
인증하기 버튼 클릭하면 인증 완료 후 로그인 페이지로 이동
> (user/prontend) 회원가입 프론트엔드 구현 

- assets/css/signup.css
- assets/js/login.js
- assets/js/logout.js
- assets/js/signout-email-verify.js
- assets/js/signout.js
- assets/js/signup.js
- assets/views/common/header.html
- assets/views/main.html
- assets/views/my-info.html
- assets/views/signout-email-verify.html
- assets/views/signup.html
- src/user/user.controller.ts
- src/user/user.service.ts
* 진행사항
1) 로그인 시 헤더 버튼  SHOW & HIDE
2) 로그아웃 누르면 쿠키 삭제
3) 회원탈퇴 시 이메일 인증 후 회원탈퇴 진행
4) 회원가입 시 ALERT 표시 대신 TEXT로 표시
* 특이사항
1) 백엔드 에러로 수정
> (user/prontend) 로그아웃 , 회원탈퇴, 회원가입 시 ALERT 대신 TEXT로 표시

- assets/css/common.css
- assets/js/account.js
- assets/js/my-info.js
- assets/views/my-info.html
- src/accounts/entities/account.entity.ts
> (myinfo/front) 내 계좌 이름 수정 및 삭제 API 연결

- assets/css/common.css
- assets/css/my-info.css
- assets/js/account.js
- assets/js/common.js
- assets/js/my-info.js
- assets/views/my-info.html
- src/user/dto/update-user.dto.ts
- src/user/user.controller.ts
**진행사항**
1. 내 정보 수정 시 비밀번호 체크 모달 추가 
- 비밀번호 체크 API 별도 분리
**특이사항**
1. 내 정보 수정하는 모달 만들어서 백엔드 연결부탁드립니다. @kimminjae981002
> (myinfo/fix) 내 정보 수정 시 비밀번호 체크 모달 추가

- assets/css/common.css
- assets/css/main-page.css
- assets/css/my-comments.css
- assets/css/my-info.css
- assets/js/account.js
- assets/js/common.js
- assets/js/my-post.js
- assets/views/common/header.html
- assets/views/main.html
- assets/views/my-comments.html
- assets/views/my-posts.html
- src/post/post.controller.ts
- src/post/post.service.ts
**진행사항**
1. 내가 쓴 게시글 
- 내가 쓴 게시글 모음 확인
- 목록 클릭 시 해당 게시글 상세 이동 예정
2. 내가 쓴 댓글
- 내가 쓴 댓글 모음 확인
- 목록 클릭 시 해당 게시글 상세 이동 예정
> (myinfo/front) 내가 쓴 게시글, 댓글 페이지 구현

- assets/css/twit.css
- assets/js/common.js
- assets/js/twit/twit-detail.js
- assets/js/twit/twit.js
- assets/views/stock_main.html
- assets/views/twit/twit-detail.html
- assets/views/twit/twit-send.html
- assets/views/twit/twit.html
- src/twit/entities/twit.entity.ts
- src/twit/twit.module.ts
- src/twit/twit.service.ts
- src/user/user.service.ts
- 보낸쪽지, 받은쪽지 조회 프론트 작업
- 쪽지 상세조회 프론트 작업
- twit 엔티티 닉네임 컬럼 추가
- 모듈고유성을 위한 서비스 작업 수정
> (Twit/front) 쪽지 프론트 및 api수정

- assets/css/my-info.css
- assets/js/my-info.js
- assets/js/signup.js
- assets/views/my-info.html
- src/user/dto/update-password.dto.ts
- src/user/dto/update-user.dto.ts
- src/user/user.controller.ts
- src/user/user.service.ts
* 진행사항
1) 내 정보 수정(닉네임, 휴대폰 번호) 구현
2) 비밀번호 변경 구현
3) 비밀번호 찾기, 회원 찾기 폴더 생성
* 특이사항
1) 내 정보 수정 시 닉네임 휴대폰 번호 데이터 받아 오기
2) 폴더 명 변경 (-)하이픈으로 해야됨.
> (user/prontend) 내 정보 수정 , 비밀번호 변경 , 비밀번호와 회원 찾기 폴더 생성

- assets/css/my-info.css
- assets/js/common.js
- assets/js/my-info.js
- assets/js/signin-email-verify.js
- assets/js/signout-email-verify.js
- assets/js/signout.js
- assets/js/signup.js
- assets/views/common/header.html
- assets/views/my-info.html
- assets/views/signin-email-verify.html
- assets/views/signout-email-verify.html
- assets/views/signup.html
- src/auth/auth.controller.ts
- src/auth/social-kakao-strategy.ts
- src/user/dto/create-user.dto.ts
- src/user/dto/found-password.dto.ts
- src/user/dto/update-password.dto.ts
- src/user/dto/update-user.dto.ts
- src/user/user.controller.ts
- src/user/user.service.ts
* 진행사항
1) 백엔드 비밀번호 찾기 임시 비밀번호 메일 발송
2) 내 정보 수정 시 원래 데이터  
3) 회원탈퇴 버튼 생성
* 특이사항
1) 프론트엔드 비밀번호 찾기 진행 예정
2) 회원탈퇴 버튼 위치 수정 예정
> (user/prontend) 비밀번호 찾기, 내 정보 수정 데이터 받기, 회원탈퇴

- assets/css/common.css
- assets/css/twit.css
- assets/js/common.js
- assets/js/twit/twit-detail.js
- assets/js/twit/twit-send.js
- assets/js/twit/twit.js
- assets/views/twit/twit-detail.html
- assets/views/twit/twit-send.html
- assets/views/twit/twit.html
- src/common/dto/paginate.dto.ts
- src/main.ts
- src/twit/twit.controller.ts
- src/twit/twit.service.ts
- 페이지네이션 공통작업
- 보낸쪽지, 받은쪽지 삭제 프론트작업
- 쪽지 보내기 프론트 작업
> (Twit/delsend) 페이지네이션 작업, 쪽지 삭제, 쪽지보내기 프론트작업

- assets/js/common.js
- assets/views/sw.js
- package-lock.json
- package.json
- src/app.module.ts
- src/auth/auth.module.ts
- src/auth/social-naver.strategy.ts
- src/comment/comment.module.ts
- src/comment/comment.service.ts
- src/comment/entities/comment.entity.ts
- src/configs/database.config.ts
- src/post/post.module.ts
- src/post/post.service.ts
- src/push/dto/create-push.dto.ts
- src/push/dto/update-push.dto.ts
- src/push/entities/push.entity.ts
- src/push/push.controller.ts
- src/push/push.module.ts
- src/push/push.service.ts
- src/push/test/push.controller.spec.ts
- src/push/test/push.service.spec.ts
- src/stock/stock.service.ts
- src/twit/entities/twit.entity.ts
- src/user/dto/update-user.dto.ts
- src/user/entities/user.entity.ts
- src/user/user.controller.ts
- src/user/user.service.ts
**진행사항**
1) 푸시 알림 엔티티 추가 
- 알림 조회 시 필요한 데이터를 저장하는 테이블 추가 
2) 푸시 알림 기능 1차 작업
- 다른 사람이 내 게시글에 댓글을 작성하면 알림 
**특이사항**
- 일부 로직 수정 필요
> (push) 알림 Entity 추가 및 푸시 알람 1차 작업

- assets/js/common.js
- src/comment/comment.module.ts
- src/comment/comment.service.ts
- src/push/push-config.ts
- src/push/push.module.ts
- src/push/push.service.ts
- src/user/entities/user.entity.ts
- src/user/user.controller.ts
- src/user/user.service.ts
**진행사항**
1) 푸시 관련 공통 코드는 config 파일로 관리
2) 유저 구독 정보 추가하는 부분 로직 수정
> (push) 푸시 관련 코드 리팩토링

- assets/js/my-comments.js
- assets/js/my-post.js
- assets/views/my-comments.html
- assets/views/my-info.html
- assets/views/my-posts.html
- src/comment/comment.controller.ts
- src/comment/comment.service.ts
- src/common/slack.alarm.interceptor.ts
- src/post/post.controller.ts
- src/post/post.service.ts
- src/push/push.service.ts
**진행사항**
1. 페이지네이션
- 내가 쓴 게시글/댓글 페이지네이션 적용 
2. 알림 삭제 스케쥴 추가
- 매일 자정 읽은 알림 중 생성일 기준 24시간 이상 지난 알림 삭제
> (mycontents/push) 내가 쓴 게시글, 댓글 페이지네이션 및 알림 삭제 스케쥴 추가

- assets/js/notice-main.js
- assets/js/notice-page.js
- assets/views/common/header.html
- roll이 user일 경우 글쓰기, 수정, 삭제 버튼 안보이게
- roll이 admin일 경우 글쓰기, 수정, 삭제 버튼 보이게
> Notice/front) 공지사항 버튼 숨기기

- assets/js/push-noti.js
- src/app.module.ts
- src/comment/comment.service.ts
- src/common/global-exceptions.filter.ts
- src/common/slack/slack.alarm.interceptor.ts
**진행사항**
1. 슬랙 500 알림 메시지 로직 
- 기존 인터셉터 사용 -> 필터로 변경
2. 알림 클릭 시 해당 컨텐츠로 연결
> (push) 슬랙 알림 로직 및 알림 관련 내용 수정

- assets/js/post-read.js
- assets/js/post-update.js
- assets/views/post-update.html
진행 사항
- 게시물의 수정 기능 페이지 구현
특이사항
> (post/view) 게시물의 수정기능 구현

- assets/js/post-read.js
- assets/views/post-read.html
진행사항
- 구성요소에 user-id 을 주어서 로그인한 사용자와 비교하여 버튼을 활성화
- 로그인 유저의 댓글, 게시물일경우 해당 수정,삭제 버튼 활성화
- 로그인 유저 이외의  댓글, 게시물일경우 쪽지 보내기 활성화
> (Post/view) 사용자에 따른 요소 활성화

- assets/js/notice-main.js
> (Notice/front) 공지사항 빈페이지 문구 추가

- assets/js/post-posting.js
- assets/js/post-read.js
- src/comment/comment.controller.ts
- src/post/post.controller.ts
진행 사항
- 댓글 작성 및 수정에 유효성검사 추가
- 공백으로만 댓글 작성 불가
> (Post/view)댓글에 유효성검사 적용

- assets/js/signin-email-verify.js
- assets/js/signout-email-verify.js
- assets/views/common/header.html
- package-lock.json
- package.json
- src/email/email.service.ts
- src/user/user.controller.ts
- src/user/user.service.ts
* 진행사항
1) 회원가입 시 axios 응답 안 나온 거 수정
2) 네이버 소셜 로그인은 서비스 목적만 배포 가능해서 소셜로그인 버튼 숨김
* 특이사항
1) 구글 소셜 로그인 수정 중
> (user/prontend) 회원가입 시 이메일인증 , 네이버 버튼 숨김

- assets/css/common.css
- assets/css/my-account.css
- assets/js/account.js
- assets/js/stock-myaccount.js
- assets/views/stock-myaccount.html
- src/accounts/accounts.controller.ts
- src/accounts/accounts.service.ts
- src/order/entities/stockHolding.entity.ts
- src/order/order.service.ts
- src/stock/entities/stock.entity.ts
**진행사항**
1. 내 계좌 가치 산정
- 포인트 + 매수 주문중인 금액 + 보유중인 현재의 주식 가치 
** 보유중인 현재의 주식 가치 
- 종목별 현재 보유중인 주식 수 * 전일 종가(공공 데이터) 
2. 보유 주식 평가
- 현재 주식 가치 - 투자 원금
** 투자원금 
- 종목별 완료된 매수 주문 총 금액 / 총 수량 = 1주 당 평균 매입 단가
- 현재 보유중인 주식 수 * 1주 당 평균 매입 단가
> (account/add) 내 계좌 가치 산정 및 보유주식 추가

- assets/js/account.js
- assets/js/stock-main.js
- assets/views/stock_main.html
- src/accounts/accounts.service.ts
- src/accounts/entities/account.entity.ts
- src/stock/stock.module.ts
- src/stock/stock.service.ts
**진행사항**
1. 랭킹 산정 로직
- 1순위 해당 계좌의 총 가치 평가하여 높은 가치의 계좌가 우선 순위
- 계좌의 가치 평가액이 동일할 경우 계좌 생성일 기준 짧은 투자기간을 가진 계좌가 우선 순위
2. 랭킹 기준 날짜 표기
- updatedAt 기준으로 날짜를 표기
> (rank/fix) 랭킹 산정 로직 수정 및 업데이트 날짜 표기

- assets/js/stock-main.js
- src/auth/social-google.strategy.ts
> (deploy/test) 구글 로그인 콜백 주소 수정

- README.md
- assets/js/post-read.js
- assets/js/stock-detail-my.js
- assets/views/stock-detail-my.html
- docker-compose.yaml
- package-lock.json
- package.json
- redis-cli.txt
- src/configs/env-validation.config.ts
- src/order/order.module.ts
- src/order/order.processor.ts
- src/order/order.service.ts
- redis클라우드서버 연결
- nestjs bull도입(Queue)
> (Redis/bull) 매도/매수 bull로 Queue도입

- assets/css/search-result.css
- assets/js/notice-main.js
- assets/js/search-result.js
- assets/js/search.js
- assets/views/common/header.html
- assets/views/search-result.html
- src/app.module.ts
- src/search/database.module.ts
- src/search/database.service.ts
- src/search/search.controller.ts
- src/search/search.module.ts
- src/search/search.service.ts
> (Notice/front) 통합검색기능구현

- src/news/news.service.ts
스케줄 수정 
기존 스케줄이 30분마다 초당 한번씩 작동하는 스케줄이었기 때문에 오작동 유발
30분마다 한번씩으로 수정
> Fix[news/crawl] 뉴스 크롤링 스케줄 수정

- assets/js/common.js
- assets/js/stock-main.js
- assets/js/twit/twit.js
* 진행사항
1) 모의투자, twit 들어가면 로그인이 필요합니다 alert창과 unauthorized alert창이 뜨는 거 하나로 수정
> (user/prontend) unauthorized 두번 뜨는 거 alert 수정

- assets/js/found-user.js
* 진행사항
1) 이메일 찾기 버튼 클릭 시 한 번만 먹히는 버그 수정
2) 소셜 로그인 시 휴대폰 번호 이메일 찾기 못하게 수정
> (user/prontend) 휴대폰 번호로 이메일 찾기 버그 수정

- assets/js/common.js
> (user/prontend) 브라우저 닫을 시 로그아웃 기능

- assets/css/stock_main.css
- assets/js/common.js
- assets/js/search.js
- assets/js/stock-common.js
- assets/js/stock-main.js
1) 모의투자 검색 시 공백 및 특수문자 유효성 처리
2) 뒤로가기 새로고침 시 로그인 풀리는 부분 수정
@kimminjae981002 해당 부분 하드코딩되어 있는거 같은데 로직 수정이 필요합니다.
3) 주식 메인 페이지 퍼센트에 따라 색깔 표기
> (bug/fix) 유저 테스트 수정

- assets/js/stock-common.js
- assets/js/stock-search.js
- assets/views/stock-order.html
**진해사항**
1. 검색 키워드에 한글 안되는 부분 수정 
2. 전체 주문내역 누락 수정
> (bug/fix) 검색 키워드 수정 및 전체 주문내역 추가

- src/news/news.controller.ts
> (news/crawl) 샘플용 뉴스크롤링 삭제
